Repository WingsDao/griffin-consensus-poc, pull requests merged in 2019-03, with the labels that each got.

#1 Added transport 1st and 2nd levels
  base/transport.js
  repl.js
Labels: enhancement, help wanted

#5 Added onchain actions: tx, vote, stake.
  core/Account.js
  core/genesis.js
  lib/helpers.js
  lib/types.js
  package-lock.json
  package.json
  test/unit/account.js
  test/unit/accounts.js
Labels: help wanted

#6 Added core/pool functionality
  core/pool.js
  data/.gitignore
Labels: enhancement

#13 Moved delegate and bp to clients/, changed network/ to services/
  bp.js
  clients/block-producer.js
  clients/delegate.js
  core/blockchain.js
  services/observer.js
  services/sync.js
  services/waiter.js
Labels: enhancement, help wanted
