Repository WingsDao/griffin-consensus-poc, pull requests merged in 2019-04, with the labels that each got.

#14 Sign and verifying messages
  core/account.js
  test/unit/account.js
Labels: enhancement

#22 Added trial version of genesis library and unit test for it.
  lib/genesis.js
  package-lock.json
  package.json
  test/unit/genesis.js
Labels: help wanted

#27 Added wallet service to initialize account in one place
  clients/block-producer.js
  clients/delegate.js
  services/wallet.js
Labels: enhancement

#21 Clients
  README.md
  bp.js
  clients/block-producer.js
  clients/delegate.js
  core/account.js
  core/blockchain.js
  core/chaindata.js
  core/file-peer.js
  core/pool.js
  data/.gitignore
  genesis.json
  index.js
  lib/events.js
  lib/genesis.js
  lib/helpers.js
  lib/math.js
  package-lock.json
  package.json
  runner.js
  services/observer.js
  services/waiter.js
  services/wallet.js
  test/unit/genesis.js
Labels: enhancement, help wanted

#29 Producer selection algorithm.
  clients/block-producer.js
  clients/delegate.js
  runner.js
  services/observer.js
Labels: help wanted

#32 Added ping mechanics for address pinging
  lib/events.js
  runner.js
  services/observer.js
Labels: enhancement

#30 Core service
  core/account.js
  core/blockchain.js
  genesis.json
  lib/constants.js
  package.json
  test/unit/account.js
  test/unit/blockchain.js
Labels: help wanted

#33 Changed frn generation function, implemented cert number
  clients/block-producer.js
  core/account.js
  lib/math.js
Labels: enhancement, help wanted

#35 Improved lib/genesis to support multi-role records
  core/account.js
  core/blockchain.js
  core/db.js
  genesis.json
  lib/genesis.js
  lib/parser.js
  package.json
  test/unit/account.js
  test/unit/blockchain.js
  test/unit/genesis.js
Labels: enhancement, help wanted

#34 Leveldb integration
  bp.js
  clients/block-producer.js
  clients/delegate.js
  core/account.js
  core/blockchain.js
  core/chaindata.js
  core/db.js
  core/file-peer.js
  core/pool.js
  genesis.json
  index.js
  lib/genesis.js
  lib/parser.js
  package-lock.json
  package.json
  services/observer.js
  services/sync.js
  test/unit/account.js
  test/unit/blockchain.js
  test/unit/genesis.js
Labels: enhancement
